version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: investorpro-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: investorpro
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: investorpro-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: